# Generated by Django 4.2.3 on 2023-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="Price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
