# Generated by Django 4.2.3 on 2023-09-06 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_remove_product_price_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Price",
        ),
    ]
