# Generated by Django 4.2.3 on 2023-09-06 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
