# Generated by Django 4.2.3 on 2023-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_remove_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="shop/images"),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
    ]
